# metadata_profiles/jpg_general_profile.py

JPG_GENERAL_PROFILE = {
    "ImageName": {"label": "Image Name", "unit": None},
    "AcquisitionDate": {"label": "Acquisition Date", "unit": None},
    "DimensionX": {"label": "Image Width", "unit": "pixels"},
    "DimensionY": {"label": "Image Height", "unit": "pixels"},
    "CameraMake": {"label": "Camera Make", "unit": None},
    "CameraModel": {"label": "Camera Model", "unit": None},
    "Software": {"label": "Software", "unit": None},
    "Artist": {"label": "Artist", "unit": None},
    "Copyright": {"label": "Copyright", "unit": None},
    "Description": {"label": "Description", "unit": None},
    "ResolutionX": {"label": "Resolution X", "unit": "dpi"},
    "ResolutionY": {"label": "Resolution Y", "unit": "dpi"},
    "GPSLatitude": {"label": "GPS Latitude", "unit": "deg"},
    "GPSLongitude": {"label": "GPS Longitude", "unit": "deg"},
    "Caption": {"label": "Caption / Abstract", "unit": None},
    "Keywords": {"label": "Keywords", "unit": None},
    "Byline": {"label": "Byline (Author)", "unit": None},
    "BylineTitle": {"label": "Byline Title", "unit": None},
    "Credit": {"label": "Credit", "unit": None},
    "Source": {"label": "Source", "unit": None},
    "IPTCCopyrightNotice": {"label": "IPTC Copyright Notice", "unit": None},
    "City": {"label": "City", "unit": None},
    "ProvinceState": {"label": "Province / State", "unit": None},
    "Country": {"label": "Country", "unit": None},
    "ObjectName": {"label": "Object Name", "unit": None},
    "SpecialInstructions": {"label": "Special Instructions", "unit": None},
    "XMPUsageTerms": {"label": "XMP Usage Terms (License)", "unit": None},
    "XMPRights": {"label": "XMP Rights", "unit": None},
    "XMPSubject": {"label": "XMP Subject", "unit": None},
}
